### ISSUE TITLE
sign ups don't work as expected sometimes

### ISSUE THREAD

**Issue by kaden-weber** [ManhanGroup/massbuilds#37]
**Describe the bug**
This might just be a problem with development user databases, but adding a new user can sometimes result in an unable to sign-in report. Checking on the backend, it is trying to use id's that already exist. 

**Steps to reproduce**
Walk us through how you revealed the bug.

**Expected behavior**
We shouldn't be repeating ID's on the backend 

**Server output**
```
Started POST "/users" for 127.0.0.1 at 2023-09-03 18:58:27 +0000
Processing by UsersController#create as JSONAPI
  Parameters: {"data"=>{"attributes"=>{"email"=>"kweber142+1@gmail.com", "password"=>"[FILTERED]", "first_name"=>"password-reset", "last_name"=>"testing", "municipality"=>nil, "role"=>nil, "agency"=>"SLOCOG", "request_verified_status"=>false, "created_at"=>nil}, "type"=>"users"}}
  TRANSACTION (0.2ms)  BEGIN
  User Exists? (0.3ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "kweber142+1@gmail.com"], ["LIMIT", 1]]
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."authentication_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["authentication_token", "-zj1cBewUu49VEVRUJaB"], ["LIMIT", 1]]
  User Create (4.2ms)  INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at", "authentication_token", "first_name", "last_name") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["email", "kweber142+1@gmail.com"], ["encrypted_password", "$2a$11$NmNRUsN8f9.cxpvP8di2/.YGQ/mNuj/H9t.F786LJKXwhKWdaBi0a"], ["created_at", "2023-09-03 18:58:27.385992"], ["updated_at", "2023-09-03 18:58:27.385992"], ["authentication_token", "-zj1cBewUu49VEVRUJaB"], ["first_name", "password-reset"], ["last_name", "testing"]]
  TRANSACTION (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 136ms (ActiveRecord: 5.1ms | Allocations: 4577)


  
ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(4) already exists.
):
  
app/controllers/users_controller.rb:35:in `create'
Started POST "/users" for 127.0.0.1 at 2023-09-03 18:58:36 +0000
Processing by UsersController#create as JSONAPI
  Parameters: {"data"=>{"attributes"=>{"email"=>"kweber142+1@gmail.com", "password"=>"[FILTERED]", "first_name"=>"password-reset", "last_name"=>"testing", "municipality"=>nil, "role"=>nil, "agency"=>"SLOCOG", "request_verified_status"=>false, "created_at"=>nil}, "type"=>"users"}}
  TRANSACTION (0.2ms)  BEGIN
  User Exists? (0.3ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "kweber142+1@gmail.com"], ["LIMIT", 1]]
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."authentication_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["authentication_token", "-Wgi7N1_h_rStRwWJL2K"], ["LIMIT", 1]]
  User Create (0.9ms)  INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at", "authentication_token", "first_name", "last_name") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["email", "kweber142+1@gmail.com"], ["encrypted_password", "$2a$11$77aVoR2nmSG3kiQEtXO/CeFhbslo7qc6NQbpO4qqu6TeGyMHVZmSy"], ["created_at", "2023-09-03 18:58:36.324238"], ["updated_at", "2023-09-03 18:58:36.324238"], ["authentication_token", "-Wgi7N1_h_rStRwWJL2K"], ["first_name", "password-reset"], ["last_name", "testing"]]
  TRANSACTION (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 123ms (ActiveRecord: 1.8ms | Allocations: 2569)


  
ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(5) already exists.
):
  
app/controllers/users_controller.rb:35:in `create'
Started POST "/users" for 127.0.0.1 at 2023-09-03 18:58:38 +0000
Processing by UsersController#create as JSONAPI
  Parameters: {"data"=>{"attributes"=>{"email"=>"kweber142+1@gmail.com", "password"=>"[FILTERED]", "first_name"=>"password-reset", "last_name"=>"testing", "municipality"=>nil, "role"=>nil, "agency"=>"SLOCOG", "request_verified_status"=>false, "created_at"=>nil}, "type"=>"users"}}
  TRANSACTION (0.2ms)  BEGIN
  User Exists? (0.3ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "kweber142+1@gmail.com"], ["LIMIT", 1]]
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."authentication_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["authentication_token", "GiioBJ2qGgzkNZVFDgLo"], ["LIMIT", 1]]
  User Create (1.9ms)  INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at", "authentication_token", "first_name", "last_name") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["email", "kweber142+1@gmail.com"], ["encrypted_password", "$2a$11$oHTcCdqgFLWU32PK2wheLO0CMUdT6kPNUe1i.SiPJICeeAMJXBXxq"], ["created_at", "2023-09-03 18:58:38.310106"], ["updated_at", "2023-09-03 18:58:38.310106"], ["authentication_token", "GiioBJ2qGgzkNZVFDgLo"], ["first_name", "password-reset"], ["last_name", "testing"]]
  User Load (0.2ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
  TRANSACTION (0.5ms)  COMMIT
[active_model_serializers]   Development Load (0.4ms)  SELECT "developments".* FROM "developments" WHERE "developments"."deleted_at" IS NULL AND "developments"."user_id" = $1  [["user_id", 6]]
[active_model_serializers]   Edit Load (0.2ms)  SELECT "edits".* FROM "edits" WHERE "edits"."deleted_at" IS NULL AND "edits"."user_id" = $1  [["user_id", 6]]
[active_model_serializers] Rendered UserSerializer with ActiveModelSerializers::Adapter::JsonApi (2.66ms)
Completed 201 Created in 166ms (Views: 2.5ms | ActiveRecord: 3.8ms | Allocations: 3120)


Started POST "/my/users/sign_in" for 127.0.0.1 at 2023-09-03 18:58:38 +0000
Processing by SessionsController#create as JSON
  Parameters: {"user"=>{"password"=>"[FILTERED]", "email"=>"kweber142+1@gmail.com"}, "session"=>{"user"=>{"password"=>"[FILTERED]", "email"=>"kweber142+1@gmail.com"}}}
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1  [["email", "kweber142+1@gmail.com"]]
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "kweber142+1@gmail.com"], ["LIMIT", 1]]
  TRANSACTION (0.3ms)  BEGIN
  User Update (0.4ms)  UPDATE "users" SET "sign_in_count" = $1, "current_sign_in_at" = $2, "last_sign_in_at" = $3, "current_sign_in_ip" = $4, "last_sign_in_ip" = $5, "updated_at" = $6 WHERE "users"."id" = $7  [["sign_in_count", 1], ["current_sign_in_at", "2023-09-03 18:58:38.466998"], ["last_sign_in_at", "2023-09-03 18:58:38.466998"], ["current_sign_in_ip", "127.0.0.1"], ["last_sign_in_ip", "127.0.0.1"], ["updated_at", "2023-09-03 18:58:38.467208"], ["id", 6]]
  TRANSACTION (1.5ms)  COMMIT
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.06ms)
Completed 201 Created in 125ms (Views: 1.9ms | ActiveRecord: 2.7ms | Allocations: 3331)


Started GET "/users?email=kweber142%2B1%40gmail.com" for 127.0.0.1 at 2023-09-03 18:58:38 +0000
Processing by UsersController#index as JSONAPI
  Parameters: {"email"=>"kweber142+1@gmail.com"}
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "kweber142+1@gmail.com"], ["LIMIT", 1]]
  TRANSACTION (0.2ms)  BEGIN
  User Update (0.4ms)  UPDATE "users" SET "sign_in_count" = $1, "current_sign_in_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4  [["sign_in_count", 2], ["current_sign_in_at", "2023-09-03 18:58:38.493700"], ["updated_at", "2023-09-03 18:58:38.493949"], ["id", 6]]
  TRANSACTION (0.6ms)  COMMIT
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "kweber142+1@gmail.com"], ["LIMIT", 1]]
[active_model_serializers]   Development Load (0.6ms)  SELECT "developments".* FROM "developments" WHERE "developments"."deleted_at" IS NULL AND "developments"."user_id" = $1  [["user_id", 6]]
[active_model_serializers]   Edit Load (0.3ms)  SELECT "edits".* FROM "edits" WHERE "edits"."deleted_at" IS NULL AND "edits"."user_id" = $1  [["user_id", 6]]
[active_model_serializers] Rendered UserSerializer with ActiveModelSerializers::Adapter::JsonApi (3.64ms)
Completed 200 OK in 10ms (Views: 3.1ms | ActiveRecord: 2.8ms | Allocations: 2831)
```

**Comment by kaden-weber** [comment]
Closing as this is related to how a database is setup / restored from backup.
